date: "2024-01-18"
author: Jonghyun Lee
title: 'Compose and Conquer: Diffusion-Based 3D Depth Aware Composable Image Synthesis'
thumbnail: https://cdn-uploads.huggingface.co/production/uploads/60f1abe7544c2adfd699860c/-yf5DxmvTrVDfbGeLFsZd.png
link: https://huggingface.co/papers/2401.09048
summary: The paper proposes a conditional diffusion model, Compose and Conquer (CnC), that allows for the integration of control over three-dimensional object placement with disentangled representations of global stylistic semantics from multiple exemplar images. CnC utilizes depth disentanglement training and soft guidance to localize multiple conditions in a disentangled manner, enabling perception of objects at varying depths and composing localized objects with different global semantics. The code is...
opinion: placeholder
tags:
    - Computer Vision
    - Deep Learning
