author: Jonghyun Lee
date: '2024-01-18'
link: https://huggingface.co/papers/2401.09048
opinion: placeholder
summary: This paper proposes Compose and Conquer (CnC), a conditional diffusion model
  that integrates control over 3D object placement with disentangled representations
  of global stylistic semantics from multiple exemplar images. CnC utilizes depth
  disentanglement training to infer the absolute positions of unseen objects and soft
  guidance to impose global semantics on targeted regions. This framework allows for
  the localization of multiple conditions in a disentangled manner, enabling the perception
  of ...
tags:
- Computer Vision
- Deep Learning
- Explainable AI and Interpretability
thumbnail: https://cdn-uploads.huggingface.co/production/uploads/60f1abe7544c2adfd699860c/-yf5DxmvTrVDfbGeLFsZd.png
title: 'Compose and Conquer: Diffusion-Based 3D Depth Aware Composable Image Synthesis'
translated_path:
  ko: ../translated-papers/2401.09048/paper.ko.html
