name: collect_papers

on: 
  schedule:
    - cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Download daily papers
        run: |
          yesterday_date=$(date -d "yesterday 13:00" '+%Y-%m-%d')
          curl "https://huggingface.co/api/daily_papers?date=$yesterday_date" -o daily_papers.json

      - name: Write daily papers post
        run: |
          cd ./src && go run main.go parse -f ../daily_papers.json -o ../current

      - name: Commit Changes
        run: |
          git config --global user.name 'Chansung'
          git config --global user.email 'deep.diver.csp@gmail.com'
          git add .
          git commit -m "Automated report"
          git push
