name: test

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up dependencies
        working-directory: py
        run : |
          pip install -r requirements-gif.txt

      - name: test moviepy
        run: |
          python py/archive_mov_gif.py \
            --yaml-dir current \
            --gif-output-github-repo codingpot/hf-daily-paper-newsletter-tester \
            --gif-output-dir assets \
            --speedx 5
