name: test

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: setup dependencies
        working-directory: py
        run: |
          pip install -r requirements.txt

      - name: run translation jobs
        working-directory: py
        run: |
          python provision_translation_instance.py \
            --dstack-token="${{ secrets.DSTACK_TOKEN }}" \
            --github-token="${{ secrets.GH_TOKEN }}" \
            --target-archive-github-repo="codingpot/hf-daily-paper-newsletter-tester" \
            --arxiv-ids="2401.08541" "2401.07519" "2401.06951" "2401.07781" "2401.08417" "2401.08565" "2401.07004" "2401.07049" "2401.07727"
