name: test

on: 
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: setup dependencies
        run: |
          pip install arxiv-dl
          pip install nougat-ocr

      - name: clone arXiv translator repo
        run: |
          git clone https://github.com/deep-diver/arxiv-translator.git
