author: Jonghyun Lee
date: '2024-01-18'
link: https://huggingface.co/papers/2401.09048
opinion: placeholder
summary: This paper presents a conditional diffusion model that integrates control
  over three-dimensional object placement with disentangled representations of global
  stylistic semantics from multiple exemplar images. The model leverages depth disentanglement
  training and soft guidance techniques to unify localization of multiple conditions
  in a disentangled manner, resulting in a versatile framework for composing localized
  objects with different global semantics while offering perception of objects at
  v...
tags:
- Deep Learning
- Computer Vision
thumbnail: https://cdn-uploads.huggingface.co/production/uploads/60f1abe7544c2adfd699860c/-yf5DxmvTrVDfbGeLFsZd.png
title: 'Compose and Conquer: Diffusion-Based 3D Depth Aware Composable Image Synthesis'
translated_path:
  ko: ../translated-papers/2401.09048/paper.ko.html
